spring:
  datasource:
    url: jdbc:h2:mem:trackerdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: ru.test.tasktracker.model
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVm"
    expiration-minutes: 120
